source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'AUMediaPlayer_Example', :exclusive => true do
  pod "AUMediaPlayer", :path => "../"
end

target 'AUMediaPlayer_Tests', :exclusive => true do
  pod "AUMediaPlayer", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
